import { Box, Grid, Stack } from '@mantine/core'
import { GetStaticProps } from 'next'
import Head from 'next/head'

import Bio from '@shibaflog/components/BIo'
import VerticalArticleCard from '@shibaflog/components/Card/VerticalArticleCard'
import CategoryList from '@shibaflog/components/CategoryList'
import { client } from '@shibaflog/libs/client'
import { Blog, Category } from '@shibaflog/types'

type Props = {
  blog: Blog[]
  category: Category[]
}

const Home = ({ blog, category }: Props) => (
  <>
    <Head>
      <title>Shibaflog</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <Grid>
      <Grid.Col sm={12} md={8}>
        <Box component='main'>
          <Stack spacing={16}>
            {blog.map(({ title, hero, categories, publishedAt, id }) => (
              <VerticalArticleCard
                key={id}
                id={id}
                title={title}
                hero={hero}
                categories={categories}
                publishedAt={publishedAt}
              />
            ))}
          </Stack>
        </Box>
      </Grid.Col>
      <Grid.Col sm={12} md={4}>
        <Box component='aside'>
          <Stack spacing={32}>
            <Bio />
            <CategoryList category={category} />
          </Stack>
        </Box>
      </Grid.Col>
    </Grid>
  </>
)

export const getStaticProps: GetStaticProps = async () => {
  const blogData = await client.getList<Blog>({ endpoint: 'blog' })
  const categoryData = await client.getList<Category>({ endpoint: 'categories' })

  return {
    props: {
      blog: blogData.contents,
      category: categoryData.contents,
    },
  }
}

export default Home
