import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { client } from '@shibaflog/libs/client'
import { Blog } from '@shibaflog/types'

type Props = {
  blog: Blog[]
}

const Home = ({ blog }: Props) => (
  <div>
    <Head>
      <title>Shibaflog</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <main>
      <h1>Hello world</h1>
      <div>
        <ul>
          {blog.map(({ id, title }) => (
            <li key={id}>
              <Link href={`/blog/${id}`}>
                <a>{title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </main>
  </div>
)

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.getList<Blog>({ endpoint: 'blog' })

  return {
    props: {
      blog: data.contents,
    },
  }
}

export default Home
