import { GetStaticProps } from 'next'
import Head from 'next/head'

import VerticalArticleCard from '@shibaflog/components/Card/VerticalArticleCard'
import Main from '@shibaflog/components/Layout/Main'
import { getArchiveList } from '@shibaflog/libs/archive'
import { client } from '@shibaflog/libs/client'
import { Blog, Category, Archive } from '@shibaflog/types'

type Props = {
  blog: Blog[]
  categoryList: Category[]
  archiveList: Archive
}

const Home = ({ blog, categoryList, archiveList }: Props) => (
  <>
    <Head>
      <title>Shibaflog | Home</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <Main categoryList={categoryList} archiveList={archiveList}>
      {blog.map(({ title, hero, categories, publishedAt, revisedAt, id }) => (
        <VerticalArticleCard
          key={id}
          id={id}
          title={title}
          hero={hero}
          categories={categories}
          publishedAt={publishedAt}
          revisedAt={revisedAt}
        />
      ))}
    </Main>
  </>
)

export const getStaticProps: GetStaticProps = async () => {
  const allBlogData = await client.getList<Blog>({ endpoint: 'blog', queries: { limit: 3000 } })
  const categoryListData = await client.getList<Category>({ endpoint: 'categories' })
  const archiveListData = getArchiveList(allBlogData.contents)

  return {
    props: {
      blog: allBlogData.contents,
      categoryList: categoryListData.contents,
      archiveList: archiveListData,
    },
  }
}

export default Home
